### ISSUE TITLE
RDImport uses incorrect units for the --segue-level switch

### ISSUE THREAD

**Issue by ElvishArtisan** [ElvishArtisan/rivendell#451]
When using the ```--segue-level``` switch with rdimport(1), it expects the level to be in hundreds of a dBFS, rather than dBFS as stated in the man page.

**Comment by ElvishArtisan** [comment]
Already fixed in 'master'.

**Comment by workino** [comment]
Hello Problem is still present
[root@rivtest systemd]# ps ax |grep rdimport
24218 ?        Sl     0:00 /usr/local/bin/rdimport --persistent-dropbox-id=1 --drop-box --normalization-level=-13 --autotrim-level=-30 --segue-level=-2000 --segue-length=1500 --fix-broken-formats --delete-source --startdate-offset=0 --enddate-offset=0 --log-filename=LOG.log --log-directory=/home/rd --verbose MUSIC /home/rd/music_import/*

How u can see is still -2000 instead of -20 

Regards
