### ISSUE TITLE
Cannot compile Rivendell 4

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#654]
When compiling rdaudioconvert.cpp in the new QT5 based code and mp4v2 is enabled, the following error is thrown:

rdaudioconvert.cpp: In member function 'RDAudioConvert::ErrorCode RDAudioConvert::Stage1M4A(const QString&, RDWaveFile*)':
rdaudioconvert.cpp:778:52: error: cannot convert 'const QString' to 'const char*' for argument '1' to 'SNDFILE* sf_open(const char*, int, SF_INFO*)'
   if((sf_dst=sf_open(dstfile,SFM_WRITE,&sf_dst_info))==NULL) {

Note this is being compiled on the current build of CentOS 7

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in branch 'qt5'. Please test!

**Comment by WMTH** [comment]
Still receiving an error when compiling rdexport:

 

CXX      rdxport.o

rdxport.cpp: In member function ‘void Xport::XmlExit(const QString&, int, const QString&, int, RDAudioConvert::ErrorCode)’:

rdxport.cpp:468:27: error: cannot convert ‘const QString’ to ‘const char*’ for argument ‘1’ to ‘void RDXMLResult(const char*, int, RDAudioConvert::ErrorCode)’

   RDXMLResult(str,code,err);

**Comment by ElvishArtisan** [comment]
Thanks.
