### ISSUE TITLE
RdLibrary : Waveform display broken when zooming

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#835]
Hello
This issue has been seen on Rivendell 4.0.0rc0int1
When importing a 1:18:54 long sound, the waveform is incomplete when zooming more than 5 times
![Capture d’écran du 2022-10-25 22-02-52](https://user-images.githubusercontent.com/87763/197872753-a113694e-b0e5-4450-8bdd-da2bc5127983.png)
When zooming at the max, the waveform is cut earlier in time
![Capture d’écran du 2022-10-25 22-01-58](https://user-images.githubusercontent.com/87763/197872955-8a15aee4-468b-4ebf-8b8c-001ca153a613.png)
When zooming out completely, or zooming in just less than 6 times, the waveform is correct
![Capture d’écran du 2022-10-25 22-03-42](https://user-images.githubusercontent.com/87763/197873463-76429721-2d6c-475b-9a57-642d547cd077.png)

Moreover, the cursor position is imprecise compared to the time grid on the waveform view
![Capture d’écran du 2022-10-25 22-01-37](https://user-images.githubusercontent.com/87763/197873277-fad48995-f80e-47de-8552-f9ffe138ab73.png)

**Comment by jmpalmito** [comment]
+1 I can reproduce it here
V4.0.0 Beta3int3 ubuntu 22.04 LTS Rivendell-fr repo

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in b5e05a0. Please test!

**Comment by fpeyraud** [comment]
Hello
Thanks for the patch, but IMHO it is not fixed : If I understand correctly the new behavior, the zoom increase is blocked after a certain factor (the buttons Zoom up and full in are disabled), which is not really usable in the case of long sounds. We then lack timing precision when positioning markers since there may be 30" between two vertical graduation bars.
Moreover, when displaying the full waveform (full out) and clicking the "full in" button, we then have timing precision, but the truncated waveform bug pops again.

**Comment by ElvishArtisan** [comment]
>  If I understand correctly the new behavior, the zoom increase is blocked after a certain factor (the buttons Zoom up and full in are disabled)

That's correct. Unfortunately, we are up against a hard limit here in Qt's graphics rendering engine (maximum size of bitmaps). While this could in theory be worked around, it would require a complete redesign and refactoring of Rivendell's waveform generation and refactoring code. That's worth doing, but it'd be an extremely disruptive and time-consuming change that I don't want to introduce in the middle of the Release Candidate stage of the release cycle. 

Let's get v4.x out the door, then revisit this.
