### ISSUE TITLE
Switcher GPIO

### ISSUE THREAD

**Issue by glenndrives** [ElvishArtisan/rivendell#876]
On V4.0.0rc2, Linux Mint 21 Vanessa (Jammy) XFCE, when trying to add a BT ACS8.2 we are getting SQL errors on both the client and server when trying to configure:

Server:
`invalid SQL or failed DB connection[Field 'VGUEST_TYPE' doesn't have a default value QMYSQL: Unable to execute query]: insert into `VGUEST_RESOURCES` set `STATION_NAME`='rdserver',`MATRIX_NUM`=0,`NUMBER`=14
DB connection re-established
`
Client:
`invalid SQL or failed DB connection[Field 'VGUEST_TYPE' doesn't have a default value QMYSQL: Unable to execute query]: insert into `VGUEST_RESOURCES` set `STATION_NAME`='wobxam',`MATRIX_NUM`=0,`NUMBER`=15
DB connection re-established`

The serial ports are configured properly in rdadmin | Manage Hosts | Serial Ports and the proper serial port is assigned in rdadmin | Manage Hosts | Switchers GPIO

Serial connectivity has been verified with a null modem between the machines and running screen back to back.

Any insight is greatly appreciated.

Cheers!

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Fixed in 66fe9ca8. Please test!

**Comment by glenndrives** [comment]
Ran

sudo apt update

and 

sudo apt upgrade

and the problem persists. If I need to apply the patch in another way please let me know.

**Comment by ltyndale** [comment]
Glen,

The code on github has been updated, but the packages have not been 
recompiled / updated, so with just an apt upgrade you won't get the fix. 
  You'll either need to compile the source or wait for the packages to be 
updated with this fix.

> Ran
> 
> sudo apt update
> 
> and
> 
> sudo apt upgrade
> 
> and the problem persists. If I need to apply the patch in another way 
> please let me know.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/ElvishArtisan/rivendell/issues/876#issuecomment-1467956481
[2]
