### ISSUE TITLE
RDCatch does not convert to MP2 after record

### ISSUE THREAD

**Issue by ltyndale** [ElvishArtisan/rivendell#933]
Rivendell 4.1.2 - when setting rdcatch to record / save a recorded file as an MP2 in rdadmin --> Manage Hosts --> Rdcatch the resulting file in /var/snd does not appear to be converted to mp2, but stays as a linear uncompressed file.
Process to reproduce:
1 - set rdcatch to record as PCM16 in rdadmin, then have rdcatch record a short test file.  In my case I recorded a 2 minute long file.  Approximate file size of the actual cart/cut audio file after record is 24MB
2 - In rdadmin set rdcatch to record as MPEG Layer 2, 192 Kbps.  Have rdcatch record another 2 minute test file.  The resulting audio file in /var/snd after record is still 24MB.  If it had converted the file to mpeg layer 2 it should be around 6 to 7 MB, but it is not.
3 - I tried at 128 kbps.  The resulting file should have been around 4 to 5 MB, but it is still 24MB.

I have even tried restarting the services to see if restarting services would cause RDCatch to pick up the setting, it makes no difference.

I can import into the library as MP2 and it works fine.  The correct codecs are installed, mpeg layer 2 is available in rdadmin -- Manage Hosts -- Audio Resources.  So far this appears to be an issue with rdcatch.

I have also verified that this issue does not occur on Rivendell 3.6.7.

Of course storage is cheap these days, so recording as uncompressed linear audio is the better option.  I ran into this on an older system I'd upgraded with limited storage where using MPEG Layer 2 recording has been adequate for internal use for years.

**Comment by ElvishArtisan** [comment]
What is your audio card setup (HPI, JACK or ALSA) and, if HPI what model AudioScience card are you using?

**Comment by ElvishArtisan** [comment]
Confirmed here. Appears to be limited to cases where normalization is enabled in the rdcatch(1) event.

**Comment by ElvishArtisan** [comment]
Fixed in 1c40f60. Please test!

**Comment by ltyndale** [comment]
This fix is is closer, but still not working quite right.  If 
normalization is turned off it works fine for encoding to either PCM or 
MP2.  With normalization turned on it works fine for PCM.  With encoding 
to mp2 and normalization after the record the cart turns up as red in 
rdlibrary.  When going into "edit markers" on the cut it will claim 
there is no audio present, even though the file in /var/snd has a file 
length.

This is running with JackAudio.

On 2023-12-18 14:36, Fred Gleason wrote:

> Fixed in 1c40f60 [1]. Please test!
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/ElvishArtisan/rivendell/commit/1c40f60caf203a6655961c8bc3abef3391a8966d
[2] 
https://github.com/ElvishArtisan/rivendell/issues/933#issuecomment-1861431339
[3]

**Comment by alexolivan** [comment]
This one is an old one also.
I stumbled with this while testing, quite a long time ago: https://github.com/ElvishArtisan/rivendell/issues/785

I closed it since, at that time, it appeared as I was the only one affected and, since I've been using a Debian VM with Jackd (so everything software) instead of the more typical Ubuntu Studio + ASI scenario, all the way during my beta testing journey, I tended to thing my issues could be often false-positives :-/

**Comment by ElvishArtisan** [comment]
> I closed it since, at that time, it appeared as I was the only one affected and, since I've been using a Debian VM with Jackd (so everything software) instead of the more typical Ubuntu Studio + ASI scenario, all the way during my beta testing journey, I tended to thing my issues could be often false-positives :-/

It was a real bug, which I fixed; while managing to introduce a new (different) one in the process. Now fixed in 3c16e0f. Please test!

**Comment by ltyndale** [comment]
That fix seems to have worked!  I've just done multiple tests with 
rdcatch and they all worked.  Thanks so much!

On 2023-12-27 16:56, Fred Gleason wrote:

>> I closed it since, at that time, it appeared as I was the only one 
>> affected and, since I've been using a Debian VM with Jackd (so 
>> everything software) instead of the more typical Ubuntu Studio + ASI 
>> scenario, all the way during my beta testing journey, I tended to 
>> thing my issues could be often false-positives :-/
> 
> It was a real bug, which I fixed; while managing to introduce a new 
> (different) one in the process. Now fixed in 3c16e0f [1]. Please test!
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/ElvishArtisan/rivendell/commit/3c16e0f5fa5826adcc24b18e6f450d23ab88fb92
[2] 
https://github.com/ElvishArtisan/rivendell/issues/933#issuecomment-1870651424
[3]
